### ISSUE TITLE
Authentication using OAuth

### ISSUE THREAD

**Issue by inkel** [threefunkymonkeys/urlremember#1]
Add authentication using OAuth, so URLs could be filtered by users. Support only GitHub & Twitter as providers at this moment.

**Comment by inkel** [comment]
Sooooo, I think after 11 years it's safe to say this won't happen, so I'm closing this issue.

**Comment by kandalf** [comment]
> Add authentication using OAuth, so URLs could be filtered by users. Support only GitHub & Twitter as providers at this moment.

Your lack of faith is uncanny
